# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0432\u0435\u0442',
                'verbose_name_plural': '\u0421\u043e\u0432\u0435\u0442\u044b',
            },
        ),
    ]
