# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20160819_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='amount',
            new_name='money',
        ),
    ]
